name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Lint Files
      run: |
        pre-commit run --all-files
